language: bash

sudo: true

before_script:
  - sudo apt-get install -y software-properties-common
  - sudo apt-add-repository -y ppa:swi-prolog/stable
  - sudo apt-get update
  - sudo apt-get install -y swi-prolog
  - swipl --version

script:
  - swipl -s tests/tests.pl -g run_tests,halt -t 'halt(1)'

notifications:
  email: false